---
title: "Programación sesiones"
slug: programacion
---


<embed src="/programa/multinivel2019prog_sesiones2.pdf" type="application/pdf" width="90%" height="600px" />

[(programación original)](/programa/multinivel2019prog_sesiones.pdf)

<br>

<i class="fas fa-chalkboard-teacher"></i> Documentos de presentación

<i class="fas fa-book-reader"></i> Lecturas

<i class="fas fa-user-edit"></i> Evaluaciones, talleres y otros

<br>

| | | <i class="fas fa-chalkboard-teacher"></i> |<i class="fas fa-book-reader"></i> | <i class="fas fa-user-edit"></i> |
|----- | -- |-----------------|-------------------------- |-------------|
| Agosto | 6   | [**Introducción**](../docpres/01_intro/1mlmintro.html)   | [Coleman 1986](../readings/coleman1986.pdf)  | |
|        | 13 | [**Bases**](../docpres/02_bases/2mlmbases.html)   |  [Finch cap. 1, 2 & 3](../readings/finch_etal 2014cap123.pdf)    | [Práctica A: Bases](../practicas/a_introreg/a_introreg.html) |
|        | 20 | [Estimación con distintos niveles](../docpres/03_jerarquicos/3jerarquicos.html)    |      |  |
|        | 27  | [Correlación intra clase y estimación MLM](../docpres/04_icc&ranef/4icc-ranef.html)   |   | [Práctica B: Primera estimación](../practicas/b_iccranef/b_icc-ranef.html)   |
| Septiembre  | 3  | Suspensión por toma  |   |   |
|             | 10 | Suspensión por toma  |   |   |
|              | 24 | [Efectos Aleatorios](../docpres/05_ranef/5ranef.html)  |   | [Practica C: Efectos aleatorios](../practicas/c_ranef.html)  |
|              |   |    |   |  |
| Octubre   | 1  | [Ajuste y Reporte](../docpres/06_fitreport/6fitrep.html)   | [O’Conell & McCoach 7, Evaluating model fit and adequacy](../readings/OConnellchap7.pdf)   | [Practica D: Integración datos L2](../practicas/d_datosL2.html)  |
|   |   |   |    [O’Conell & McCoach 11, Reporting results from multilevel](../readings/OConnellchap8.pdf)   |   |
|   | 8  | Ronda de presentaciones grupales   |   | [Práctica E: Ajuste y reporte](https://multinivel.netlify.com/practicas/e_ajustereporte.html)  |
|   | 15  | [Interacción entre niveles](../docpres/07_interacciones/7interacciones.html)  | [Aguinis et al (2013) Best practices MLM interactions](../readings/aguinis2013crosslevel.pdf)  | [Práctica F: Interacciones entre niveles](https://multinivel.netlify.com/practicas/f_interaccion.html)   |
| Diciembre  | 10  | [Centrado](../docpres/08_centering/08centering.html)  | [Enders & Tofighi 2007) Centering predictor variables MLM](../readings/enderstofighi.pdf)  |    |
