---
title: Programa
slug: syllabus
citeproc: false
bibliography: ../static/bib/electivomultinivel.bib
csl: ../static/bib/apa.csl
nocite: '@*'
---

```{r load-libraries, message=FALSE, warning=FALSE, include=FALSE}
library(dplyr)
library(tibble)
library(pander)
```

[^courseinfo]: {-}
  `r blogdown::shortcode("courseinfo")`


# Descripción

Gran parte de la investigación sociológica hace referencia al contexto en que las personas viven y se desenvuelven, como por ejemplo lugares de trabajo, salas de clases, barrios, países. Sin embargo, modelos tradicionales como ANOVA y regresión poseen limitaciones a la hora de integrar datos en distintos niveles (individual y contextual), así como también la interacción entre ambos (por ejemplo, la relación entre nivel de vulnerabilidad de escuelas, capital cultural de los padres y rendimiento académico de estudiantes). El presente curso aborda el análisis simultáneo de datos en distintos niveles mediante modelamiento multinivel. Comienza con una problematización de la integración del contexto en el análisis sociológico de datos, para luego describir las principales características y usos de modelos multinivel.

El curso tiene una orientación práctica y aplicada a problemas de investigación en torno a los cuales se desarrollará un trabajo de investigación.


# Orientación

El presente curso se propone desarrollar en las y los estudiantes las habilidades necesarias para:

- Comprender las limitaciones de métodos de estimación tradicionales (como regresión simple) para el análisis de datos con estructuras jerárquicas.

- Entender las estructuras de datos que ameritan un análisis de tipo multinivel.

- Implementar,  interpretar y reportar análisis de modelos jerárquicos lineales y no lineales.

# Contenidos

## 1. Unidad I: Introducción a la estimación multinivel

• Datos anidados y datos agregados
• Limitaciones de métodos tradicionales para datos anidados
• Correlación intra-clase
• Predictores en distintos niveles
• Generación e importación de datos nivel 2
• Reporte

## 2. Unidad II: Profundización

• Pendiente aleatoria
• Interacción entre niveles
• Ajuste
• Centrado de variables
• Introducción a estimación con datos longitudinales

## 3. Unidad III: Aplicaciones prácticas

• En base a trabajos de alumn_s

# Metodología

El curso se organiza en sesiones semanales, con una parte lectiva seguida de una práctica. En la parte lectiva se transmiten y discuten los conceptos centrales del análisis multinivel. En la parte práctica se aplicarán los conceptos transmitidos en la parte lectiva, además de resolver dudas en el avance de los trabajos de investigación. Durante la práctica se hará énfasis en la perspectiva de ciencia abierta, que se relaciona con transparencia y reproducibilidad de los productos de investigación. En este marco utilizaremos el programa de análisis estadı́stico R (gratuito y open source) tanto para temas de análisis como también para la generación de reportes, apoyados por herramientas como Rmarkdown/Knitr. En la misma lı́nea de ciencia abierta se fomentará la colaboración entre los alumnos para que compartan los resultados de sus aprendizajes y también se evalúen mutuamente.

# Evaluación

La evaluación consistirá en la elaboración de un reporte en el formato de artículo de investigación. La evaluación será 30% la primera entrega, 40% la segunda, 20% la presentación oral del trabajo y 10% un informe de evaluación de un trabajo realizado por otros participantes del curso.

El atraso o la inasistencia asociada a la entrega de evaluaciones debe ser justificada a la secretaría de la carrera (no se aceptan justificaciones directas).  Quienes cuenten con justificación por haber faltado a alguna evaluación, tendrán la oportunidad de dar una evaluación en un nuevo plazo. De no cumplir este requisito para el caso de las entregas, se descontará 1 punto por día de atraso, con un máximo de dos días; de otra manera se asignará la nota mínima.

La sumatoria ponderada de los resultados de sus evaluaciones será su nota de presentación a examen. Podrán eximirse del examen todas aquellas personas que tengan un promedio ponderado igual o superior a 5.5 (en escala de 1.0 a 7.0). Podrán presentarse a examen de primera oportunidad todas aquellas personas que tengan un promedio ponderado igual o superior a 3.5 (en escala de 1.0 a 7.0). En caso de tener un promedio inferior a 3.5 (en escala de 1.0 a 7.0) deberá presentarse a examen de segunda oportunidad. En caso de que deba presentarse a examen, su promedio ponderado de notas del semestre equivaldrá al 60% de su nota de presentación y el examen al 40% restante. El examen será oral.

El examen de segunda oportunidad (solo para quienes no hubiesen aprobado el curso en instancias previas) será una prueba escrita donde se medirán todos los contenidos del curso.

# Varios

Las clases en general se acompañan de documentos de presentación, que estarán disponibles antes de la sesión en la página [sesiones](/programacion/), y están desarrollados con base en Rmarkdown/Xaringan ^[[`Rmarkdown/ Xaringan`](https://github.com/yihui/xaringan)] . Estos documentos no son:

-. "la clase"

-. autoexplicativos (ni aspiran a serlo)

-. "el ppt" (ni mucho menos "la ppt")


# Bibliografía
