---
title: "Trabajos"
output:
  blogdown::html_page:
    toc: true
---

<hr>

# **Grupo 1**: Migracion y vivienda en chile: Un estudio de los determinantes de los costos de arriendo en 2017

**Martín Venegas, Andreas Lafferte, Diego Esturillo & Jan Dimter**


Existe un consenso generalizado en la literatura sobre la desactualización e ineficacia de la política de regularización migratoria del país, la cual no tiene la capacidad de hacer frente a los flujos migratorios del contexto actual. Dicha situación tiene un impacto en las condiciones de vida de la población migrante en distintas fases del proceso de migración: llegada al país, permanencia en el país y salida del país. En términos de llegada y permanencia en el país la literatura sugiere una relación entre la dificultad de regularizar la situación y el acceso a derechos como salud, educación, trabajo y vivienda.
Dentro de la dimensión de vivienda, autores como Arís, Mesa & Valenzuela (2018) han diagnosticado, para Chile y países vecinos, la ausencia del derecho a la vivienda en lo que es el reconocimiento de derechos de la población migrante (p. 52). Por otro lado, autores como Link, Troncoso, Troncoso & Fundación Techo (2018) muestran problemáticas contingentes como: el hacinamiento y allegamiento, el mercado inmobiliario informal y las situaciones de abuso (p.ej renta excesiva y cambiante) que sufre la población migrante en lo que respecta a sus condiciones de habitabilidad.

Santiago y la zona norte figuran como aquellas con mayor presencia de población migrante y también con mayores tazas de problemáticas como déficit habitacional cuantitativo y hacinamiento (SJM, 2019). Sin embargo, la oferta de arriendo y sus costos parecen ser distintos en cada zona, en regiones como Antofagasta hay una baja oferta y altos costos, a diferencia de Santiago. A partir de esta situación, surgen las siguientes preguntas y sus hipótesis:

P1: ¿Cuáles son las principales determinantes que influyen en las diferencias en los costos de arriendo de la población migrante entre las distintas comunas de Chile al año 2017?

H1: Una de las principales determinantes que influyen en las diferencias en los costos de arriendo de la población migrante entre las distintas comunas de Chile al año 2017 será el porcentaje de arriendo sin contrato de la comuna. Además, el acceso a servicios básicos también será uno de los principales determinantes.

P2: ¿Cómo influye el porcentaje de arriendo sin contrato en los costos de arriendo de la de la población migrante dependiendo de la comuna?

H2: A mayor porcentaje de arriendo sin contrato habrá mayores costos de arriendo en la comuna

P3: ¿Cómo influye la cantidad de acceso a servicios en los costos de arriendo de la población migrante dependiendo de la comuna?

H3: A mayor promedio1 de acceso a servicios en la comuna habrá mayores costos de arriendo.
Ficha metodológica

**Base de datos: Casen 2017**

Alcance investigación: Exploratoria y relacional

Nivel 1: encuestados de nacionalidad no chilena. r1b. Cuando usted nació ¿en qué comuna o país vivía su madre? Respuesta en categorías nominales con especificación:

Nivel 2: comuna

Variable dependiente: “costo de arriendo”: v18. Su hogar ¿Cuánto paga de arriendo? Respuesta libre tipo numérica3

Variable independiente de hipótesis: “porcentaje arriendos sin contrato”

- v13. Su hogar, ¿bajo qué situación usa la vivienda? Respuesta en categorías nominales:

- v37. Del siguiente listado de servicios, ¿Su vivienda se encuentra a…? Responda cada alternativa 1. Sí 2. No 9. No sabe. Respuesta nominal dicotómica:

  a) ¿Menos de 8 cuadras o 1 Km de un servicio de transporte público (paradero, estación)?
  b) ¿A menos de 20 cuadras o 2,5 Km de un centro educacional (colegio o jardín infantil)?
  c) ¿A menos de 20 cuadras o 2,5 Km de un centro de salud (atención primaria o nivel superior)?
  d) ¿A menos de 20 cuadras o 2,5 Km de un supermercado, almacén o feria?
  e) ¿A menos de 20 cuadras o 2,5 Km de un cajero automático o caja vecina?
  f) ¿A menos de 20 cuadras o 2,5 Km de un equipamiento deportivo (centros deportivos, canchas, skatepark)?
  g) ¿A menos de 20 cuadras o 2,5 Km de áreas verdes (plazas o parques)?
  h) ¿A menos de 20 cuadras o 2,5 Km de equipamiento comunitario (centros vecinales, sedes sociales, biblioteca vecinal o centro cultural comunitario)?
  i) ¿A menos de 20 cuadras o 2,5 Km de una farmacia?

Variables de control:

Nivel 1: Sexo, edad, año llegada a Chile, discriminado por ser extranjero

Nivel 2: Porcentaje de subsidio de arriendos dados, porcentaje de hacinamiento

<hr>

# Grupo 2: Trato en el sistema de salud en Santiago

**Javiera Carvajal, Victor Jimenez, Karen Tapia**

- Problema de investigación: Diferencia en el trato en el sistema de salud.
- Hipótesis (multinivel): Existen diferencias de trato hacia las personas en el sistema de salud dependiendo de la comuna de residencia de esta.
- Datos a utilizar: Base de datos y libro **Desiguales (2017)**
- Principales variables:
  - Dependiente: Trato en el sistema de salud.
  - Independiente nivel 1: Rango etario, clase social, sexo.
  - Nivel 2: Comuna de residencia

<hr>
# Grupo 3: ¿Qué pueden hacer las escuelas para disminuir la desigualdad en el conocimiento cívico?

**Alejandra Delaveau, Catalina Flores, Anais Herrera y Francisco Meneses.**

- Problema de investigación: Los estudios enfocados en la temática han destacado el efecto positivo del nivel socioeconómico y de pertenecer al género femenino sobre el conocimiento cívico, así como el efecto de algunas variables contextuales. No obstante, aún no se ha evaluado qué variables correspondientes al contexto escolar pueden moderar la relación entre el nivel socioeconómico y el conocimiento cívico. La presente propuesta de investigación busca responder la siguiente pregunta ¿Qué características del colegio son capaces de reducir la diferencia en el conocimiento cívico de estudiantes de distinto origen socioeconómico?
- Hipótesis (multinivel): Se espera que un buen clima escolar, una percepción positiva de los estudiantes sobre la apertura en las discusiones en el aula y una alta cultura participativa de los estudiantes posean un efecto positivo en el conocimiento cívico, capaz de moderar el efecto del nivel socioeconómico.
- Datos a utilizar: **ICCS (2016) Chile**, donde se incorporan 5.081 estudiantes de 8°grado anidados en 178 escuelas.
- Principales variables: Conocimiento cívico (PV1CIV), género (S_GENDER), nivel socioeconómico (S_NISB), clima escolar (S_STUTREL, S_INTACT y S_ABUSE), percepcion de los estudiantes sobre la apertura en las discusiones en el aula (IS3G17A-IS3G17F) y cultura participativa de los estudiantes (IS3G21A-IS3G21E).

<hr>
# Grupo 4: Jóvenes chilenos y autoritarismo: Análisis multinivel sobre factores que predicen la actitud de los jóvenes chilenos hacia el autoritarismo

**Cristian Fuentes, Brigitte Ortiz, Guislaine Espinoza & Gabriel Fuentes**


Estudios recientes (ICCS, 2016) han señalado que las y los jóvenes de latinoamérica (siendo Chile uno de los países estudiados) muestran bajo conocimiento cívico y, a pesar de que existen posturas favorables hacia la tolerancia hacia las minorías y la equidad de género, persisten actitudes que tienden a justificar la violencia y el autoritarismo.

La literatura ha dado cuenta que existen factores que influyen en una actitud favorable hacia el autoritarismo en el gobierno por parte de los jóvenes. Factores como: relaciones familiares de corte autoritario, baja autoestima y seguridad, baja formación en educación cívica, entre otros.

En el presente estudio se busca poner a prueba los factores antes descritos, pero adicionando variables de carácter contextual, tales como la dependencia administrativa del colegio, región (colegio) y el nivel socioeconómico, esto con el fin de conocer si la actitud de los jóvenes hacia el autoritarismo depende en mayor medida de variables asociadas a los sujetos, o si estos presentan puntuaciones diferenciadas asociadas a contextos compartidos.

Nuestra hipótesis anticipa que los sujetos expuestos a relaciones familiares jerárquicas serían más propensos a sentir una baja autoestima, lo cual fomentaría una actitud positiva hacia el autoritarismo. Por otra parte, el tener una baja formación cívica fomentaría también una actitud positiva hacia el autoritarismo. Sin embargo, estas relaciones estarían agrupadas por los contextos en los cuales se desarrollan los estudiantes.

Los datos a utilizar: **“Primera Encuesta de Desarrollo Humano en Niños, Niñas y Adolescentes” del año 2017 de PNUD. **

Respecto de las variables a utilizar:

- Variables nivel 1: “Relaciones familiares jerárquicas”, “Percepción de inseguridad del estudiante” y “Formación Cívica de los estudiantes”.
- Variables Nivel 2: “Dependencia administrativa del colegio”, “Región” y “Nivel Socioeconómico”.
- Variable dependiente: “Actitud hacia el autoritarismo”.

<hr>
# Grupo 5: Satisfacción con el uso del tiempo según grupos etarios: El impacto de la clase

**Antonia Atria, Isidora Didier & Carla Maguida**

Problema de Investigación

En el último tiempo, Chile ha estado sumergido en la discusión sobre el proyecto de Ley de 40 horas, que consiste en disminuir la jornada laboral semanal de 45 a 40 horas. Durante la discusión de este proyecto, un argumento que ha resaltado sobre el resto es que los/as trabajadores/as dispondrán de más tiempo para estar con su familia, y aumentaría su tiempo de ocio. En este escenario, resulta importante examinar la satisfacción que las personas sienten de la forma en que usan su tiempo libre, y, específicamente, si está satisfacción se ve afectada por elementos estructurales, es decir, por su posición socioeconómica.

Hipótesis

A partir del problema planteado surge la hipótesis del presente estudio. Se espera que los jóvenes y los adultos jóvenes, agrupados en los tramos 15 a 24 años y 25 a 34 años, de comunas con mayores ingresos, presenten mayores niveles de satisfacción con el uso que le dan a su tiempo libre. Bajo esta misma línea, se espera que quienes presenten menores niveles de satisfacción con el uso de su tiempo libre sean adultos y adultos mayores de clase baja, agrupados en el tramo de 65 años y más.

Datos a utilizar: Base de Datos de la **Encuesta Nacional Sobre Uso del Tiempo** (INE, 2015)

Principales Variables

Para poder comprender el fenómeno, se utilizarán 2 variables independientes y 1 dependiente. Dentro de las variables independientes están la edad y la clase, mientras que la satisfacción con el uso del tiempo es la variable dependiente definida. La variable edad se considerará por tramos, los cuales estarán definidos según los datos que proporciona la encuesta, los cuales se asignan de la siguiente forma: 15 a 24 años, 25 a 34 años, 35 a 44 años, 45 a 54 años, 55 a 64 años, 65 años y más. Sin embargo, se convalidarán algunos tramos en función de la caracterización por grupos etarios. De esta forma, los jóvenes se definirán desde los 15 a 24 años, los adultos jóvenes desde los 25 a 34 años, los adultos desde los 35 a los 64 y la tercera edad se asignará al tramo 65 años y más.
En relación a la clase social como variable independiente, esta se definirá de acuerdo a sus características territoriales, es decir, a la ocupación por comuna. Se le otorgará un sentido territorial a la clase social debido a la influencia que tiene en la satisfacción con el uso del tiempo, lo cual se puede ver, por ejemplo, en el tiempo de viaje dentro de la ciudad o la disponibilidad  de áreas verdes y recreativas.
Finalmente, se definirá a la satisfacción con el uso del tiempo como la variable dependiente, la cual se construirá desde índices a partir de las siguientes preguntas del cuestionario de la ENUT:

T11. ¿Qué tan satisfecho está con el tiempo que dedica a …?:

Usted misma (o), Sólo si tiene pareja, Su pareja, Sólo si tiene hijos o hijas. Sus hijos(as),  Sólo si tiene padres. Sus padres, El trabajo, Amistades, Pasatiempos, Descanso

T12. ¿Qué tan satisfecho se siente con los siguientes aspectos de su vida?

Situación económica, Trabajo, Cantidad de tiempo libre, Calidad del tiempo libre, Equilibrio entre trabajo y vida familiar

<hr>
# Grupo 6: Sentido de pertenencia en estudiantes Chilenos.

**Benjamín Césped, Adolfo González, Camilo Lazo, Alexis Villanueva**

Nuestra propuesta de análisis multinivel consiste en explicar el sentido de pertenencia según el autor Juvonen (2006), de las y los estudiantes en chile a partir variables que hacen referencia principalmente a las relaciones entre estudiantes, relaciones estudiante-docente, y relaciones padre/madre-estudiante, variables de vulnerabilidad de los establecimientos, etc. Para tales efectos se hará uso de forma primaria de la base de datos de la **PISA 2015**: esto incluye los cuestionarios para padres/madres, cuestionarios de escuela, estudiantes y docentes.

- Como variable dependiente se considerará la variable BELONG de la base de datos PISA 2015, que se define como “sentido de pertenencia de los estudiantes en la escuela”.

- Como variables independientes de nivel uno se considerarán las siguientes variables: género; origen migrante; estudiante repitente o no; puntaje del estudiante en test de ansiedad; motivación del estudiante en la escuela; disfrute de cooperación con sus pares; valoración de la cooperación; apoyo emocional de los padres; adaptación a las instrucciones recibidas en clases; índice de estatus económico, social y cultural asociado a las/los estudiantes; recibimiento de violencia escolar.

- Con respecto a variables independientes de nivel 2 se considerarán: Tamaño de la escuela, del curso, tipo de establecimiento. Utilizando algunas variables independientes de nivel uno se pueden construir algunas variables independientes de nivel dos. Se propone: Promedio de estudiantes en cuanto a ESCS; Proporción de estudiantes según género; Proporción de inmigrantes.

Como hipótesis general se contempla: Las y los estudiantes tendrán mayores niveles de sentido de pertenencia para con el establecimiento si los estudiantes son inmigrantes, no repitentes, menos ansiosos, más motivados, que valoren y disfruten la cooperación con sus pares, si cuentan con apoyo emocional de sus padres, si tienen menos comportamientos disruptivos en clases y si reciben poca violencia escolar de parte de sus pares. Los efectos de estas variables podrían verse amplificados si es que el tamaño del curso y de la escuela es menor, si los estudiantes pertenecen al promedio de estatus socioeconómico de la escuela, si la proporción de estudiantes mujeres u hombres es mayor o menor con respecto al género del/la estudiante y a la proporción de estudiantes inmigrantes dentro de la escuela con respecto al origen (migrante o no), del estudiante.

<hr>
# Grupo 7: Bienestar en el territorio y manifestaciones de cohesión barrial en diferentes barrios del Gran Santiago: Propuestas de un modelo multinivel para la cohesión barrial

**Cristóbal Ortiz & Valentina Vásquez**

La vida urbana en el Gran Santiago está marcada por una baja cohesión barrial y diferentes manifestaciones de conflictos urbanos, mientras que los barrios se encuentran diferenciados unos de otros en un contexto de alta segregación socioespacial. En este escenario, la presente investigación busca abordar la cohesión barrial, entendiendo por ella un proceso gradual y colectivo que refiere a la disposición de los sujetos de un barrio a enfrentarse juntos a diferentes aspectos de la cotidianidad. Se propone responder a la pregunta ¿En qué medida el nivel de bienestar territorial del barrio incide en la cohesión barrial que expresan los habitantes del Gran Santiago? y la principal hipótesis que guía la investigación postula que hay mayores niveles de cohesión barrial en barrios cuyo nivel de bienestar territorial es mayor.

Para la ejecución de la investigación se emplearán modelos de análisis multinivel a partir de los datos levantados el año 2016 por el Estudio Longitudinal Social de Chile (ELSOC), cuya muestra incluye un total de 2983 casos a nivel nacional.

En consecuencia, el análisis busca relacionar la variable Bienestar Territorial, que agrupa diferentes indicadores de la calidad del territorio en cuanto a las dimensiones socioeconómica, ambiental, de infraestructura y de accesibilidad y  la variable Cohesión Barrial, la cual agrupa indicadores de sociabilidad dentro del barrio, confianza hacia los vecinos, participación barrial (en juntas de vecinos), identificación e integración al barrio. Adicionalmente, se evalúa la inclusión de variables de nivel 2 que den cuenta de los niveles de conflicto macro-social, reputación barrial y segregación urbana en los distintos barrios del Gran Santiago.

<hr>
# Grupo 8: Análisis de la preocupación del medioambiente a partir de contextos económicos nacionales

**Joaquin Quiroz – Gustavo Salinas**

- Problema de investigación: Factores que inciden en la preocupación medioambiental.

- Variables y datos a utilizar: El modelo que desarrollaremos a lo largo del curso investigara los factores con mayor incidencia en la preocupación del medioambiente. Los factores a nivel grupo que se utilizaran serán los recursos naturales del país y el gdpppp. En cuanto a los factores que se consideraran a nivel individual son los años de estudio, sexo y edad. Las fuentes de información serán la encuesta del año 2010 del issp y el banco mundial.

- H1: los países con mejor situación económica contaran con habitantes que poseen una mayor preocupación por el medioambiente, puesto que tras lograr determinado nivel de éxito económico se tiende a ver al cambio climático como la siguiente gran amenaza, en tanto factor de riesgo para el bienestar conseguido. En tanto aquellos países con peor situación económica tenderán a considerar los problemas medioambientales como un tema de menor importancia a problemas que aparecen más urgentes producto de su situación financiera.

- H2: Los países con más recursos naturales (entendiendo esto como valor de cambio) tenderán a tener menor preocupación por el medioambiente, puesto que tenderán a asociar la estabilidad de sus economías a modelos económicos extractivitas.

<hr>
# Grupo 9: Género y roles

**Marcos Benjamín Baeza Garrido y Maria Francisca**

- Problema de investigación: Se pretende investigar el efecto de la “ideología de género” en la satisfacción de mujeres con la repartición del trabajo doméstico con sus parejas. Con ideología de género abarcamos al conjunto de opiniones referidas a los roles masculinos y femeninos.

- Hipótesis (multinivel):

  - En la medida en que la brecha salarial entre hombres y mujeres disminuye, aumenta la satisfacción con la repartición del trabajo doméstico en el hogar
  - En la medida que existe un equilibrio entre hombres y mujeres en el órgano legislativo aumenta la satisfacción con la repartición trabajo doméstico en el hogar
  - A mayor integración femenina en el mercado laboral, menor satisfacción con la repartición de trabajo doméstico.
  -
- Datos a utilizar: Se utilizará la **ISSP 2012 - "Family and Changing Gender Roles IV"**.
- Principales variables:
Las variables a utilizar a nivel individual son variables de tipo ideológicas referidas a roles familiares, además de variables de tipo material.

  - Satisfacción con la vida familiar
  - División real trabajo doméstico según tipo de labor. (quién hace qué)
  - Quién tiene el salario más alto en la pareja
  - Estar demasiado cansado en el trabajo por los quehaceres del hogar.

Para el análisis multinivel se trabajará a nivel países utilizará la diferencia de sueldos entre hombres y mujeres por cada país, la participación en el mercado laboral femenina y la proporción de mujeres en el órgano legislativo.

<hr>
# Grupo 10: Satisfacción con la democracia en paises del Cono Sur.

**Roque Alfaro Navarro, Kevin Carrasco Quintanilla, Sebastián Cortínez Rojas y Francisco Delgado Munizaga.**

- Problema de investigación: El presente trabajo se enmarca en un contexto de creciente desconfianza hacia el sistema y las instituciones políticas debido a diversos escándalos de corrupción y desilusión en torno al cumplimiento de programas políticos en el Cono Sur. En ese sentido, el fenómeno a investigar será la variación de la confianza en el sistema político en países de Sudamérica, específicamente Argentina, Brasil, Chile, Perú y Uruguay. Para esto se utilizará la encuesta **LAPOP 2017**, de los países ya mencionados, que en conjunto suman un total de 8846 casos.

- Hipótesis (multinivel):   La hipótesis que se planteará es que los paises de América del Sur que presentan mayor desconfianza hacia el sistema político son aquellos que presentan mayores casos de corrupción de las autoridades y menores índices de satisfacción personal.

- Principales variables: Satisfacción con la democracia (dependiente), Percepción de la corrupción política, Satisfacción personal, País, Sexo y Edad.

# Grupo 11: ¿Qué peso tiene lo organizacional y económico en la ocurrencia de las huelgas extralegales en Chile?: Un análisis regional

**Valentina Andrade, Matías Montero y Carlos Budnevich**

Las huelgas laborales permiten dar cuenta del grado de conflictividad entre trabajadores y empleadores (Burawoy, 1981). En general, estas provienen del fracaso de una negociación colectiva que es, una instancia reglada por las leyes laborales que intenta generar acuerdos sobre algunas condiciones de trabajo y empleo. Si la negociación no llega a su objetivo, los trabajadores votan dos opciones: se acepta la última oferta del empleador o se comenzará con una huelga. Pero esta no es la única opción. En contextos donde la institucionalidad laboral es altamente restrictiva como en Chile (Waas, 2012) se ha podido evidenciar el aumento de huelgas fuera de la ley (Armstrong & Águila, 2006) o extra-legales (Medel, Pérez, Velásquez, & Morales, 2017; OHL, 2017).

En Chile, estas transformaciones han provocado que el estudio de la huelga se haya vuelto relevante: desde investigaciones que reconstruyen el conflicto laboral (Armstrong & Águila, 2006), describen el último ciclo huelgístico (Aravena & Núñez, 2009), su relación en el contexto neoliberal (Aguilar & Henríquez, 2017; Gaudichaud, 2015), los resultados de las huelgas (Ratto, 2017), las dinámicas de la huelga legal (Gutiérrez Crocco, 2017) y extra-legal (Pérez, Medel, & Velásquez, 2015). Sin embargo, a diferencia de la literatura internacional (Franzosi, 1989; Jansen, Akkerman, & Vandaele, 2017; Kelly, 2012), poco se ha debatido sobre los factores que explican la incidencia de la huelga. Un esfuerzo ha sido el de Medel y Pérez (2017), quienes abordan como ciertas características del régimen de trabajo y de la organización sindical se asocian con las huelgas extra-legales, relegando el peso de la economía que hasta entonces había tenido (Hyman, 1989).

La investigación a desarrollar busca debatir sobre los factores que inciden en las ocurrencia de las huelgas extra-legales. Con la particularidad, como ha propuesto Franzosi (2006), de considerar aspectos contextuales de donde ocurre la huelga como el lugar geográfico. Así, distintos estudios cuantitativos sobre las huelgas han mostrado que los ciclos de protesta laboral tienen cierta regularidad y prominencia según el lugar (e.g., país, región) (Jansen, 2014). En consecuencia, la presente investigación buscará evaluar la relación entre factores empresa, con predictores como el tipo de organización sindical, tamaño del sindicato, número de trabajadores involucrados en la huelga, tamaño de la empresa; a nivel de las regiones, con predictores como tasa de sindicalización, presencia de federaciones y centrales, desempleo, inflación y PIB de la región. Para poner a prueba empíricamente rasgos individuales y contextuales de manera simultánea, proponemos realizar un modelo de regresión logística multinivel empleando los datos del Observatorio de Huelgas Laborales (2017), a modo de dilucidar diferencias vinculadas a factores contextuales del territorio o región, junto con las variables a nivel empresa esbozadas anteriormente.

Hipótesis

H1: La presencia del sindicato a nivel de la empresa se asocia negativamente con la
probabilidad de ocurrencia de una huelga extra-legal

H2: Existe una asociación positiva entre la inflación de la región y la probabilidad de ocurrencia de una huelga extralegal

H3: La relación positiva entre tamaño de empresa y ocurrencia de huelga extralegal es
moderada negativamente por la tasa de sindicalización de la región.
