---
title: "Preocupación medioambiental"
author: "Joaquín Quiroz & Gustavo Salinas"
date: "7/10/2019"
output: html_document
---
## Introducción
La preocupación por el medioambiente puede ser definida como la percepción de que el medio ambiente natural está siendo amenazado por la acción humana (Franzen & Meyer, 2010). Actualmente, la temática ha cobrado mucha importancia a nivel planetario, situación que puede vislumbrarse, de un lado, por las masivas manifestaciones que reclaman por el cuidado al medio ambiente, y por los tratados que diversos países han establecido para paliar los efectos nocivos de los patrones de producción y consumo. En este contexto, la investigación en torno a los estudios de preocupación medio ambiental ha cobrado mucha relevancia, desarrollando asociaciones tanto con variables macro como de nivel micro (Franzen & Meyer, 2010).

De acuerdo a Mayerl y Best (2018), la teoría en torno a la preocupación medioambiental pueden separarse en tres vertientes: (1) la hipotesis de la globalización, (2) la hipótesis de la riqueza y (3) la hipótesis postmaterialista. Cabe destacar que ninguna de estas teorías ha sido capaz de explicar satisfactoriamente la preocupación medioambiental, mostrando la necesidad de "difuminar" las diferencias habidas en cada una de estas perspectivas (e.g. Mayerl & Best, 2018).  

La primera de ellas establece que la preocupación por el medioambiente es independiente de la riqueza del país, de manera que todos los países tendrían algún grado de preocupación. En cambio, la segunda de las teorías mencionadas, menciona que la preocupación medioambiental estaría más arraigada en países con mayor riqueza. Es decir, determinadas condiciones económicas generaría, o darían posibilidad, a un tipo de conducta "pro-ambiental". Según Mayerl & Best (2018), dentro de esta perspectiva hay dos tipos de aproximaciones dependiendo del nivel de la variable independiente. Así, en primer lugar, se puede encontrar una aproximación que establece que a cierto nivel de riqueza alcanzado, los factores materiales se vuelven menos importantes, mientras que cobran mayor importancia problemas como el de la preocupación medioambiental (Inglehart & Flanagan, 1987). Por otra parte, también es posible establecer relaciones con variables independientes de nivel micro -e.g. nivel socioeconómico-.Fred Pampel (2014), ha sugerido que educación e ingresos son posibles de considerar dentro del SES, mostrando una relación significativa con preocupación ambiental.  

La tercera y última perspectiva muestra que, una vez cubiertas algunas de las necesidades básicas de la población, esta tendería a preocuparse más del medioambiente. No obstante, a diferencia de la hipótesis anterior, cuyo punto de partida es semejante al recientemente expuesto, esta señalaría que no habría una relación directa entre riqueza del país y actitud ambiental, "interponiéndose" entre ellas la presencia de determinado valores.

La siguiente investigación pretende trabajar a partir de algunas consideraciones de las teorías anteriores, a partir del la encuesta ISSP -International Social Survey Programa- del año 2010 y datos del banco mundial. Así por ejemplo, se utilizarán, entre las variables macro, el GDPpp -gross domestic product per cápita-, el número de recursos naturales por país y el coeficiente GINI. De otro lado, en las variables individuales, se considerarán los años de escolaridad alcanzados, así como variables demográficas tales como el sexo y la edad de los encuestados.

Algunos estudios han utilizado el gross domestic product, encontrando relaciones fuertes con preocupación medioambiental (Franzen & Meyer, 2010). Esto es, países con mayor GDP per cápita muestran una mayor preocupación por el medio ambiente. Por otra parte, la cantidad de recursos naturales puede ser interpretada como la riqueza material potencial que posee un país. De manera que la cantidad de recursos disponibles puede interpretarse como la capacidad potencial de la economía de un país. La explotación de estos recursos podría causar mayor preocupación medio ambiental, dado los impactos negativos sociales y ambientales.

Además, es interesante agregar que Mayerl & Best (2018) indican que la tendencia vislumbrada entre los países -i.e. mientras más ricos los países mayor la preocupación ambiental-, también se manifestaría al interior de cada uno de estos. De manera, que los sectores socioeconómicos más ricos poseerían mayor preocupación ambiental que los pobres. Esto se relaciona directamente con la desigualdad al interior de los países, donde la brecha entre los niveles socioeconómico crearía oportunidades de acceso diferenciadas. De esta manera, se ha decidido incluir el GINI para ver cómo inciden los niveles de desigualdad sobre la preocupación ambiental.

Por otra parte, años de escolaridad, sexo y edad corresponden a variables independientes de nivel individual. De acuerdo a Franzen y Meyer (2010), la educación es una importante medio desde donde las personas reciben herramientas que le permiten percibir con mayor notoriedad los problemas del medio ambiente, de manera que podría estar positivamente vinculada.

Sobre edad -age effect- la evidencia parece estar dividida. Mientras algunos estudios muestran que los jóvenes poseen mayor preocupación medioambiental, otros muestran tendencias en U -no lineales- (Franzen & Meyer, 2010). Por otra parte, género ha sido la variable de estructura social más abordada (Dietz, Stern & Guagnano, 1998). Es así que diversos estudios han mostrado que las mujeres poseen mayor preocupación medioambiental que los hombres (Franzen & Meyer, 2010; Xiao & McCright, 2015).  

La pregunta sería la siguiente: ¿Cómo inciden estas variables sobre preocupación ambiental?

## Objetivos e hipótesis
A partir de lo anteriormente mencionado, es posible señalar las siguientes hipótesis:

H1: A mayor nivel educacional, mayor preocupación en el medio ambiente.

H2: Las mujeres se preocupan más en el medio-ambiente que los hombres.

H3: A menor edad -dentro del rango de edades- mayor preocupación en el medio ambiente.

H4: A mayor preocupación GDPpp, mayor preocupación medio ambiental

H5: A mayor cantidad de recursos naturales, mayor es la preocupación medio ambiental

H6: A mayor GINI, mayor preocupación ambiental.

## Datos, variables y métodos

### Presentación de la base de datos

En el presente estudio, se utilizaron distintas bases de datos para variables micro y macro. Para las variables de nivel 1 se utilizó la encuesta del ISSP -internacional survey social programme- del año 2010. Para las variables de nivel 2, en tanto, se utilizaron bases de datos del banco mundial -consultar años-.

El N general corresponde a 47087 casos. Hay, además, una cantidad de 34 países a considerar.   

### Variables 
El modelo se construyó a partir de siete variables. Contempla tres variables de nivel 1 -"años de educación", "nivel socioeconómico" y "sexo" y "edad"-, tres de nivel 2 -"número de recursos naturales", "Grow domestic product per cápita" y "coeficiente GINI"- y una dependiente -"preocupación ambiental"-.

#### Variable dependiente
Preocupación ambiental: se elaboró un índice sumativo con nueve preguntas cuyas respuestas comprendían cinco categorías, donde 1 significa muy de acuerdo y 5 muy en desacuerdo. Para la construcción del índice, se consideraron los ítems: "Modern science will solve our environmental problems with little change to our way of life" (Q9c), "We worry too much about the future of the environment and not enough about prices and jobs today" (Q10a), "People worry too much about human progress harming the environment" (Q10c), "In order to protect the environment [COUNTRY] needs economic growth" (Q11c), "It is just too difficult for someone like me to do much about the environment" (Q13a), "There are more important things to do in life than protect the environment" (Q13c), "There is no point in doing what I can for the environment unless others do the same" (Q13d), "Many of the claims about environmental threats are exaggerated" (Q13e), "I find it hard to know whether the way I live is helpful or harmful to the environment" (Q13f).El alpha de Cronbach resultó de .65, por lo cual se podría decir que el alpha es insuficiente para el estudio.

#### Variables independientes
Como ya se mencionó, las variables de nivel 1 son tres. En primer lugar, educación, cuyo rango va desde 0 a 15 años escolaridad; en segundo lugar, sexo, una variable de dos categorías que fue transformada a dummy -donde 0 es hombre y 1 es mujer-; y, en tercer lugar, edad, una variable continua que va desde los 16 a 61.

Las variables de nivel 2, por su parte, también son tres. El número de recursos naturales va de un rango desde 0 a 7819,286. El grow domestic product per cápita va de 5468,306 hasta 57965,3 . En tanto que el mínimo del coeficiente Gini es 25.6 y el máximo 63.4. -Véanse descriptivos generales-.

#### Método estadístico de análisis

El modelo estadístico a utilizar corresponde al modelos multinivel, donde las variables de nivel micro corresponden a años de escolaridad, sexo y edad, mientras que las de nivel macro están constituidas por el número de recursos naturales, el grow domestic product per cápita y el coeficiente Gini.

## Resultados
En primer lugar, la correlación intra clase del modelo resultó de 0.132, lo cual quiere decir que el 13.2% de la varianza de preocupación ambiental se relaciona con el país. 

En la tabla se muestran los diversos modelos realizados para conocer el tamaño y la significación de los efectos de las variables independientes sobre la preocupación ambiental. Se muestran los modelos con variables de nivel micro y de nivel macro.

Como se sostuvo, la hipótesis 1 corresponde a que "a mayor educación, mayor preocupación ambiental". Como se puede observar, en el modelo 2 muestra que por cada unidad que aumenta "años de escolaridad" la preocupación ambiental aumenta .27 unidades. El efecto es significativo (p<.001), es decir, los datos a nivel muestral serían representativos de la población. El modelo 4 muestra que, al considerar las variables de nivel 1 y 2 al mismo tiempo, la relación se mantiene. Sin embargo, sube en el modelo con pendiente aleatoria, a .29 y baja en el modelo 6.

Por otra parte, puede observarse que, en todos los modelos, el "gender efect" muestra que las mujeres tienen mayor preocupación ambiental respecto de los hombres, mostrando que por cada unidad de cambio en mujeres, la preocupación ambiental aumenta en .77 unidades respecto de los hombres. La situación se mantiene en todos los modelos, siendo significativa estadísticamente. De esta manera, se comprueba la hipótesis 2.

La variable edad, no obstante, parece mostrar una relación muy baja (-.01), aunque significativa en todos los modelos. De esta manera, si bien puede estar mostrando una relación, esta no es lo suficientemente sustancia como para afirmar con seguridad la hipótesis 3.

En cuanto a las variables de nivel 2 es posible mencionar que la única que resultó ser significativa fue la relación que se establece entre el grow domestic product per cápita y la preocupación ambiental, aunque su tamaño de efecto es ínfimo. -Explicar más cosas-. El número de recursos naturales, por su parte, en ninguno de los modelos resultó ser significativo y sus efectos fueron demasiado bajos, indicando que por cada unidad de cambio en número de recursos naturales la preocupación ambiental aumentaba .03 unidades.

Por último, el coeficiente gini no mostró significación estadística y su tamaño de efecto no fue grande. De esta manera se rechaza la hipótesis.


## Resumen y conclusiones
En resumen, del estudio se deduce que las variables de nivel 1 lograron explicar mejor la preocupación ambiental que las de nivel 2, a excepción de la variable edad. Dentro de las variables 1, la que mayor efecto poseía era género, donde se señaló que las mujeres poseían mayor preocupación ambiental que los hombres en todos los modelos. Además sus efectos eran significativos, es decir, que el efecto muestral era representativo de lo ocurrido en la población. Le secundaba, respecto del tamaño del efecto, la variable años de educación. 

Se observa además que las variables de nivel 2 tuvieron o muy poco efecto, pese a ser significativas, o no tener ni un efecto importante ni significancia estadística. De este modo, GDPpp era la única variables que poseía significancia estadística, pero con un resultado muy pequeño.Además, para un próximo estudio se descartaría el uso del coeficiente gini.

Se advierte aquí que el estudio tuvo, entre sus limitaciones, el uso de un índice sumativo con una consistencia interna inferior a los números óptimos -.7-. De este se deduce que, en una segunda oportunidad, se deben elegir mejor cada una de las variables para armar tal índice. 

# Bibliografía
- Franzen, A. & Meyer, R. (2010). Environmental Attitudes in Cross-National Perspective: A Multilevel Analysis of the ISSP 1993 and 2000. European Sociological Review, 26(2): 219-234.
- Mayerl, J. & Best, H. (2018). Two Worlds of Environmentalism? Empirical analyses on the complex relationship between Post-Materialism, National Wealth and Environmental Concern. Nature and Culture, 13(2): 208-231
- Pampel, F. (2014). The Varied Influence of SES on Environmental Concern, 95(1):57-75.
- Xiao, C. & McCright, A. (2015). Gender Differences in Environmental Concern: Revisiting the Institutional Trust Hypothesis in the USA, 47(1):17-37.
